[build]
  publish = "." # This tells Netlify to publish the root directory
  command = "echo 'No build command needed for static site'" # A dummy command

[functions]
  directory = "nonexistent-functions-directory" # Point to a directory that doesn't exist
  # Or, if you want to be explicit about not building functions:
  # external_node_modules = [] # This can sometimes help prevent function detection
  # included_files = []