[build]
  command = "echo 'Installing Python dependencies...' && python3 -m pip install -r netlify/functions/requirements.txt --target=./.netlify/functions/ && echo 'Dependencies installed.'"
  functions = "netlify/functions"
  publish = "."

[functions]
  # This is the new, specific way Netlify requires Python version to be defined.
  # The version is now specified within a nested object under 'functions.python'.
  # This structure is required even if 'external_node_modules' is not used.
  [functions.python]
    version = "3.10" # Specify your desired Python version here (e.g., "3.9", "3.10", "3.11")
