[build]
  command = "echo 'Installing Python dependencies...' && python3 -m pip install -r netlify/functions/requirements.txt --target=./.netlify/functions/ && echo 'Dependencies installed.'"
  functions = "netlify/functions"
  publish = "."

[functions]
  [functions.python]
    version = "3.10" # Ensure this matches your Python version

# Explicitly define the 'generate_news' function handler
# The format is 'filename.function_name'
[[functions]]
  function = "generate_news" # This matches the filename 'generate_news.py'
  handler = "generate_news.generate_news" # This means 'generate_news.py' and the function 'generate_news' inside it
