[build]
  # Netlify build configuration
  # If you continue to get "Failed to parse configuration", ensure no hidden characters
  # were introduced during copy-paste. Sometimes re-typing the file manually helps.
  command = "echo 'Installing Python dependencies...' && python3 -m pip install -r netlify/functions/requirements.txt --target=./.netlify/functions/ && echo 'Dependencies installed.'"
  functions = "netlify/functions"
  publish = "."

[functions]
  python_version = "3.10" # Changed to 3.10. Ensure this is a version supported by Netlify.
